# Generated by Django 4.1.7 on 2023-03-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_on_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='on_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventory.employee'),
        ),
        migrations.AlterField(
            model_name='productprototype',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productmodel'),
        ),
    ]
