# Generated by Django 4.1.7 on 2023-03-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_on_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='write_off',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
